// Official Universal Dynamic Report Typst Template
// PT Bali Towerindo Sentra Tbk - Enterprise Operations Command Center

#set page(
  paper: "a4",
  flipped: {{IS_LANDSCAPE}},
  margin: (x: 1.5cm, top: 1.5cm, bottom: 1.5cm),
  header: align(right)[
    #text(size: 8pt, fill: rgb("#64748b"))[
      PT Bali Towerindo Sentra Tbk | Enterprise Operations & Intelligence Report
    ]
  ],
  footer: [
    #line(length: 100%, stroke: 0.5pt + rgb("#cbd5e1"))
    #v(3pt)
    #grid(
      columns: (1fr, 1fr),
      align: (left, right),
      [
        #text(size: 7.5pt, fill: rgb("#94a3b8"))[
          Dokumen Laporan Resmi — PT Bali Towerindo Sentra Tbk (Generated by AI Multi-Agent Engine).
        ]
      ],
      [
        #text(size: 7.5pt, fill: rgb("#94a3b8"))[
          Sistem Operasi Korporat BaliTower — Rahasia & Terlindungi
        ]
      ]
    )
  ]
)

#set text(
  font: ("Segoe UI", "Roboto", "Liberation Sans", "Arial"),
  size: 8.5pt,
  fill: rgb("#1e293b")
)

#let doc_status = "{{STATUS}}"
#let status_color = if doc_status == "COMPLETED" or doc_status == "RESOLVED" or doc_status == "PASSED" { rgb("#16a34a") } else if doc_status == "CRITICAL" or doc_status == "ALERT" or doc_status == "REJECTED" { rgb("#dc2626") } else { rgb("#0284c7") }
#let status_bg = if doc_status == "COMPLETED" or doc_status == "RESOLVED" or doc_status == "PASSED" { rgb("#f0fdf4") } else if doc_status == "CRITICAL" or doc_status == "ALERT" or doc_status == "REJECTED" { rgb("#fef2f2") } else { rgb("#f0f9ff") }
#let status_border = if doc_status == "COMPLETED" or doc_status == "RESOLVED" or doc_status == "PASSED" { rgb("#bbf7d0") } else if doc_status == "CRITICAL" or doc_status == "ALERT" or doc_status == "REJECTED" { rgb("#fecaca") } else { rgb("#bae6fd") }

// Main Document Container
#block(width: 100%)[
  // Header Kop Surat Resmi PT Bali Towerindo Sentra Tbk
  #grid(
    columns: (1.3fr, 1fr),
    align: (left, right),
    [
      #text(size: 14pt, weight: "bold", fill: rgb("#0f172a"))[PT BALI TOWERINDO SENTRA TBK]\
      #v(-2pt)
      #text(size: 8.5pt, weight: "semibold", fill: rgb("#0284c7"))[TELECOMMUNICATION INFRASTRUCTURE & FIBER OPTIC SOLUTIONS]\
      #v(2pt)
      #text(size: 7.5pt, fill: rgb("#64748b"))[
        Wisma Kodel Lantai 6, Jl. H.R. Rasuna Said Kav. B-4\
        Karet Kuningan, Setiabudi, Jakarta Selatan 12920, Indonesia\
        Telepon: (021) 522-8888 | www.balitower.co.id\
        #text(weight: "medium", fill: rgb("#334155"))[{{DIVISION_NAME}}]
      ]
    ],
    [
      #text(size: 13pt, weight: "bold", fill: rgb("#0284c7"))[{{REPORT_TITLE}}]\
      #text(size: 8pt, weight: "bold", fill: rgb("#475569"))[{{REPORT_SUBTITLE}}]\
      #v(3pt)
      #rect(
        stroke: status_border,
        radius: 4pt,
        fill: status_bg,
        inset: (x: 8pt, y: 6pt),
        align(left)[
          #grid(
            columns: (72pt, 1fr),
            row-gutter: 2.5pt,
            [#text(size: 7.5pt, weight: "bold", fill: rgb("#475569"))[ID Laporan:]],
            [#text(size: 8pt, weight: "bold", fill: rgb("#0369a1"))[{{REPORT_ID}}]],
            [#text(size: 7.5pt, weight: "bold", fill: rgb("#475569"))[Waktu Terbit:]],
            [#text(size: 7.5pt, weight: "medium")[{{GENERATED_AT}}]],
            [#text(size: 7.5pt, weight: "bold", fill: rgb("#475569"))[Klasifikasi / Status:]],
            [#text(size: 7.5pt, weight: "bold", fill: status_color)[{{STATUS}}]]
          )
        ]
      )
    ]
  )

  #v(6pt)
  #line(length: 100%, stroke: 1.2pt + rgb("#0284c7"))
  #v(6pt)

  // Dynamic Metadata Section (Pills / Cards)
  {{METADATA_SECTION}}

  // Dynamic Executive Summary Section
  {{SUMMARY_SECTION}}

  #v(4pt)
  #text(size: 9.5pt, weight: "bold", fill: rgb("#0f172a"))[{{TABLE_TITLE}}]
  #v(3pt)

  // Universal Dynamic Table
  #table(
    columns: ({{COLUMNS_SPEC}}),
    align: ({{ALIGN_SPEC}}),
    stroke: (x, y) => if y == 0 { (bottom: 1.5pt + rgb("#0284c7")) } else { (bottom: 0.5pt + rgb("#e2e8f0")) },
    fill: (x, y) => if y == 0 { rgb("#0f172a") } else if calc.even(y) { rgb("#f8fafc") } else { white },
    inset: (x: 4.5pt, y: 5.5pt),
    
    // Dynamic Headers
    {{TABLE_HEADERS}},
    
    // Dynamic Rows
    {{TABLE_ROWS}}
  )

  #v(8pt)

  // Dynamic Footer Notes & Verification Box
  #grid(
    columns: (1.5fr, 1fr),
    gutter: 12pt,
    [
      #rect(
        width: 100%,
        stroke: rgb("#e2e8f0"),
        radius: 4pt,
        fill: rgb("#f8fafc"),
        inset: 7pt,
        [
          #text(size: 7.5pt, weight: "bold", fill: rgb("#334155"))[Catatan Sistem Integritas Operasional:]\
          #v(2pt)
          #text(size: 7pt, fill: rgb("#64748b"), style: "italic")[
            Dokumen ini dihasilkan secara otomatis melalui introspeksi langsung basis data DuckDB PT Bali Towerindo Sentra Tbk oleh AutoRestock-Agent. Seluruh catatan bersifat valid, terenkripsi, dan mencerminkan status operasional saat waktu terbit.
          ]
        ]
      )
    ],
    [
      #rect(
        width: 100%,
        stroke: rgb("#e2e8f0"),
        radius: 4pt,
        fill: rgb("#ffffff"),
        inset: 7pt,
        align(center)[
          #text(size: 7.5pt, weight: "bold", fill: rgb("#0f172a"))[Pengesahan AI Agent]\
          #v(14pt)
          #line(length: 75%, stroke: 0.6pt + rgb("#94a3b8"))
          #text(size: 7pt, weight: "bold", fill: rgb("#0284c7"))[Digital Stamp & Audit Token]\
          #text(size: 6.5pt, fill: rgb("#64748b"))[{{AUDIT_TOKEN}}]
        ]
      )
    ]
  )
]
